Updated PRE-RC

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -91,6 +91,7 @@ endif
 # copy the dylib and change its install names
 
 define install_osx_libraries
+    @echo "work on $(dylib)"
     $(shell $(INSTALL) -m 755 $(dylib) $(macosx_bundle_path)/MacOS)
     $(shell $(INSTALL_NAME_TOOL) -change $(dylib) @executable_path/$(notdir $(dylib)) $(macosx_bundle_path)/MacOS/ultrastardx)
     $(shell $(INSTALL_NAME_TOOL) -id @executable_path/$(notdir $(dylib)) $(macosx_bundle_path)/MacOS/$(notdir $(dylib)))
@@ -98,8 +99,12 @@ define install_osx_libraries
 endef
 
 define rename_secondary_osx_libraries
+    @echo "change the install name for $(linked_dylibs_2)"
     $(shell $(INSTALL_NAME_TOOL) -change $(linked_dylibs_2) @executable_path/$(notdir $(linked_dylibs_2)) $(macosx_bundle_path)/MacOS/$(notdir $(dylib)))
 endef
+
+USE_OSX_PACKAGING=@USE_OSX_PACKAGING@
+USE_OSX_PACKAGING_LIBDIR=@USE_OSX_PACKAGING_LIBDIR@
 
 #################################################
 # general targets
@@ -374,8 +379,8 @@ OTOOL := /usr/bin/otool
 INSTALL_NAME_TOOL := /usr/bin/install_name_tool
 # hdiutil: Mac OS X disk image tool
 HDIUTIL := /usr/bin/hdiutil
-# finkLibDir := path for libraries installed using fink
-finkLibDir := /sw/lib
+# pkgingLibDir := path for libraries installed using packaging system
+pkgingLibDir := @USE_OSX_PACKAGING_LIBDIR@
 
 #################################################
 # Mac OS X app-bundle
@@ -411,56 +416,146 @@ macosx-app: all
 
 # final messages
 	@echo ""
-	@echo "Mac OS X application created."
+	@echo "Mac OS X application created (UltraStarDeluxe.app)."
+	@echo "Using @USE_OSX_PACKAGING@ with libdir @USE_OSX_PACKAGING_LIBDIR@"
 	@echo "Please report issues to the developer team, preferably mischi."
 	@echo "Have fun."
 	@echo ""
 
+# use pkg-config. The one in the app bundle may already be changed
+ifeq ($(USE_OSX_PACKAGING), brew)
+AVCODECLIBPATH := /$(shell pkg-config --libs-only-L  libavcodec | cut -f 2- -d '/')
+endif
+
+ifeq ($(USE_OSX_PACKAGING), fink)
+AVCODECLIBPATH := $(shell pkg-config --libs-only-L  libavcodec | cut -f 4-5 -d '/' | cut -f 1 -d ' ')
+endif
+
+AVCODECLIB := $(AVCODECLIBPATH)/libavcodec.dylib
+
 .PHONY: macosx-standalone-app
 macosx-standalone-app: macosx-app 
-# Create double clickable standalone (does not need fink) Mac OS X 
-# application. Not fully test, but should work on 10.5.
+# Create double clickable standalone Mac OS X application.
+# Not fully test, but should work on 10.5.
 
 	@echo ""
 	@echo "Creating the standalone Mac OS X application"
 	@echo ""
 
+ifeq ($(USE_OSX_PACKAGING), brew)
+	@echo "avcodec lib found: $(AVCODECLIB)"
+endif
+ifeq ($(USE_OSX_PACKAGING), fink)
+	@echo "avcodec lib found: $(finkLibDir)/$(AVCODECLIB)"
+endif
 # work on the dylibs in $(macosx_bundle_path)/MacOS/ultrastardx
+	@echo "[generic] copying libs of ultrastardx"
 	$(foreach dylib,$(shell $(OTOOL) -L $(macosx_bundle_path)/MacOS/ultrastardx | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
 
 # work on the secondary dylibs from ffmpeg
 # libavcodec references all tertiary libraries of the ffmpeg libs
-	$(foreach dylib,$(shell $(OTOOL) -L $(finkLibDir)/libavcodec.dylib   | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+ifeq ($(USE_OSX_PACKAGING), brew)
+	@echo "[brew] copying libs of libavcodec"
+	$(foreach dylib,$(shell $(OTOOL) -L $(AVCODECLIB) | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+endif
+ifeq ($(USE_OSX_PACKAGING), fink)
+	@echo "[fink] copying libs of libavcodec"
+	$(foreach dylib,$(shell $(OTOOL) -L $(finkLibDir)/$(AVCODECLIB) | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+endif
+
 # same procedure in libfaac. it gets libgnugetopt
-	$(foreach dylib,$(shell $(OTOOL) -L $(finkLibDir)/libfaac.dylib      | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+	@echo "[generic] copying libs of libfaac"
+	$(foreach dylib,$(shell $(OTOOL) -L $(pkgingLibDir)/libfaac.dylib      | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
 
-# same procedure for tertiary libs in SDL_image
-	$(foreach dylib,$(shell $(OTOOL) -L $(finkLibDir)/libSDL_image.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+# same procedure for tertiary libs in SDL2_image
+	@echo "[generic] copying libs of libSDL2_image"
+	$(foreach dylib,$(shell $(OTOOL) -L $(pkgingLibDir)/libSDL2_image.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
 
-# X11 libs as well, because users may not have installed it on 10.4
-	$(foreach dylib,$(shell $(OTOOL) -L /usr/X11R6/lib/libX11.dylib  | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+# same procedure for secondary libs in libtiff
+	@echo "[generic] copying libs of libtiff"
+	$(foreach dylib,$(shell $(OTOOL) -L $(pkgingLibDir)/libtiff.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
 
-# libpcre.dylib must be installed extra, since it is not linked to the executable but opened using dlopen
-	$(shell $(INSTALL) -m 755 $(finkLibDir)/libpcre.dylib $(macosx_bundle_path)/MacOS)
-	$(shell $(INSTALL_NAME_TOOL) -change $(finkLibDir)/libpcre.dylib @executable_path/libpcre.dylib $(macosx_bundle_path)/MacOS/libpcre.dylib)
+# same procedure for secondary libs in libfreetype
+ifeq ($(USE_OSX_PACKAGING), brew)
+	@echo "[brew] copying libs of libfreetype"
+	$(foreach dylib,$(shell $(OTOOL) -L $(pkgingLibDir)/libfreetype.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+endif
+ifeq ($(USE_OSX_PACKAGING), fink)
+	@echo "[fink] copying libs of libfreetype"
+	$(foreach dylib,$(shell $(OTOOL) -L $(finkLibDir)/freetype219/lib/libfreetype.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+endif
+
+# same procedure for secondary libs in libfontconfig
+ifeq ($(USE_OSX_PACKAGING), brew)
+	@echo "[brew] copying libs of libfontconfig"
+	$(foreach dylib,$(shell $(OTOOL) -L $(pkgingLibDir)/libfontconfig.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+endif
+ifeq ($(USE_OSX_PACKAGING), fink)
+	@echo "[fink] copying libs of libfontconfig"
+	$(foreach dylib,$(shell $(OTOOL) -L $(finkLibDir)/fontconfig2/lib/libfontconfig.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+endif
+
+ifeq ($(USE_OSX_PACKAGING), fink)
+	# same procedure for secondary libs in libzvbi
+	@echo "[fink] copying libs of libzvbi"
+	$(foreach dylib,$(shell $(OTOOL) -L $(brewLibDir)/libzvbi.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+
+	# same procedure for secondary libs in libquvi
+	@echo "[fink] copying libs of libquvi"
+	$(foreach dylib,$(shell $(OTOOL) -L $(brewLibDir)/libquvi.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+
+	# same procedure for secondary libs in libssh2
+	@echo "[fink] copying libs of libssh2"
+	$(foreach dylib,$(shell $(OTOOL) -L $(brewLibDir)/libssh2.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+	
+	# same procedure for secondary libs in libcaca
+	@echo "[fink] copying libs of libssh2"
+	$(foreach dylib,$(shell $(OTOOL) -L $(brewLibDir)/libcaca.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+
+	# same procedure for secondary libs in libbluray
+	@echo "[fink] copying libs of libblueray"
+	$(foreach dylib,$(shell $(OTOOL) -L $(brewLibDir)/libbluray.dylib | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+endif
+
+#	X11 libs as well, because users may not have installed it.
+	@echo "[xquartz] copying libs of libX11"
+	$(foreach dylib,$(shell $(OTOOL) -L /opt/X11/lib/libX11.6.dylib  | grep version | cut -f 1 -d ' ' | grep -v \/System\/Library | grep -v \/usr\/lib),$(install_osx_libraries))
+
+	@echo ""
+	@echo "libpcre.dylib must be work on additionally, since it is not linked to the executable but opened using dlopen"
+	$(shell $(INSTALL) -m 755 $(pkgingLibDir)/libpcre.dylib $(macosx_bundle_path)/MacOS)
+	$(shell $(INSTALL_NAME_TOOL) -change $(pkgingLibDir)/libpcre.dylib @executable_path/libpcre.dylib $(macosx_bundle_path)/MacOS/libpcre.dylib)
 	$(shell $(INSTALL_NAME_TOOL) -id @executable_path/libpcre.dylib $(macosx_bundle_path)/MacOS/libpcre.dylib)
 
+# do  not forget to sign the code
+#	codesign -f -s USDX-codesign UltraStarDeluxe.app
+
 # final messages
+	@echo ""
 	@echo "Standalone Mac OS X application created."
 	@echo ""
 
 .PHONY: macosx-dmg
 macosx-dmg: macosx-standalone-app
+	@if test -d "/Volumes/UltraStarDeluxe"; then\
+		echo "Error: there is already a disk mounted on /Volumes/UltraStarDeluxe";\
+		exit 1;\
+	fi
 	$(RM) UltraStarDeluxe.dmg
 	$(RM) UltraStarDeluxe.sparseimage
 	$(HDIUTIL) create -type SPARSE -size 100m -fs HFS+ -volname UltraStarDeluxe -ov UltraStarDeluxe.sparseimage
 	$(HDIUTIL) attach UltraStarDeluxe.sparseimage
+	/bin/ln -s /Applications /Volumes/UltraStarDeluxe/Applications
 	/bin/cp -R UltraStarDeluxe.app /Volumes/UltraStarDeluxe
 #	/bin/cp ultrastardx/icons/UltraStarDeluxeVolumeIcon.icns /Volumes/UltraStarDeluxe/.VolumeIcon.icns
 #	/Developer/Tools/SetFile -a C /Volumes/UltraStarDeluxe/.VolumeIcon.icns /Volumes/UltraStarDeluxe
 	$(HDIUTIL) detach /Volumes/UltraStarDeluxe
 	$(HDIUTIL) convert UltraStarDeluxe.sparseimage -format UDBZ -o UltraStarDeluxe.dmg
 	$(RM) UltraStarDeluxe.sparseimage
+
+	@echo ""
+	@echo "DMG Disk image created (UltraStarDeluxe.dmg)."
+	@echo ""
 
 # remove Mac OS X apllication bundle and disk image
 .PHONY: clean-macosx
